---
- name: Install To-Do App on new web-server
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: Install Git and Python311
    become: yes
    ansible.builtin.yum:
      name: 
        - git
        - python311
      state: latest

  - name: Install Poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: /home/ec2-user/.local/bin/poetry