name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag todo-app:test --target test .
      - run: docker run todo-app:test
  deploy:
    name: Build and publish build artefact to Docker
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/fix-poetry-package-error'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - run: docker build --tag ${{ secrets.DOCKER_USERNAME }}/todo-app:latest --target production .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
            version: 1.9.8
      - run: terraform init
      - run: terraform apply -auto-approve -var prefix=pl
        env:
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_oauth_client_id: ${{ secrets.OAUTH_CLIENT_ID }}
          TF_VAR_oauth_client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
      - run: curl -dH -X POST "$(terraform output -raw cd_webhook_url)"
        