name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag todo-app:test --target test .
      - run: docker run todo-app:test
  deploy:
    name: Build and publish build artefact to Docker
    runs-on: ubuntu-20.04
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/module-12'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - run: docker build --tag ${{ secrets.DOCKER_USERNAME }}/todo-app:latest --target production .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
      - run: terraform init
      - run: terraform apply -auto-approve -var prefix=pl
      - run: curl -dH -X POST '$(terraform output -raw cd_webhook_url)'
        